### PR TITLE
Thuy - Frompt 1: Change empty results message

### PR DESCRIPTION
**Pull request by thuycao-gs**
Hi Mr. Huy @huynguyen-codeengine,
This is my PR for prompt 1. Could you consider and give me comments.
Thank you.

Steps to Reproduce:
 1. Start up the portal and log in as an Administrator.
 2. Go to the Control Panel -> Content -> Web Content.
Make sure there is no Web Content or Folders. 

Expected Result: The message "No web content was found" is displayed. 

Actual Result: The message "no-web-content-was-foundd" is displayed

### CODE REVIEW

**Comment by huynguyen-codeengine** [comment]
Please explain how did you come up with this solution ?

**Comment by thuycao99** [comment]
> Please explain how did you come up with this solution ?

**Comment by thuycao99** [comment]
> Please explain how did you come up with this solution ?

I was checked in that module, I saw it in language.properties file, it declares "no-web-content-was-found" like a key and also assigns value for that key correct with the expected result. I try and it works with my expectation.

@huynguyen-codeengine Do you have another solution?

**Comment by huynguyen-codeengine** [comment]
It's ok. Looks good to me.

**Pull request closed without merging**
