### PR TITLE
Thuy: Prompt 2.2: Fix the default results per page and number of folders.

### PR DESCRIPTION
**Pull request by thuycao-gs**
Hello @huynguyen-codeengine,
This is my PR for prompt 2.2.
Could you please consider and let me know if it has any problem?
Thanks.

Steps to reproduce:
1. Add a Documents and Media portlet.
2. Add 7 folders in the DM portlet.
3. Click the configuration of DM.
4. Select 5 of "Maximum Entries to Display "
5. Click Save and refresh the page.

Expected result:
The default results per page are 5 and 5 folders are displayed.

Actual result:
The default results per page and number of folders displayed do not changed.

### CODE REVIEW

**Comment by huynguyen-codeengine** [comment]
Could you explain your solution ?

**Comment by thuycao99** [comment]
> Could you explain your solution ?

Yes. 
I check in "configuration.jsp" of the portlet, the numbers selected show correctly. I saw in this has a portlet instance object "dlPortletInstanceSettings". I try to get the number by "lPortletInstanceSettings.getEntriesPerPage()" in this file and other files in portlet and it returns the number I selected.

I check in "view-entries.jsp", I saw in the SearchContainer, but it shows the default number "SearchContainer.DEFAULT_DELTA", I update by lPortletInstanceSettings.getEntriesPerPage(). Now it works with my expectation.

**Comment by thuycao99** [comment]
> Could you explain your solution ?

Yes. 
I check in "configuration.jsp" of the portlet, the numbers selected show correctly. I saw in this has a portlet instance object "dlPortletInstanceSettings". I try to get numbers by "lPortletInstanceSettings.getEntriesPerPage()" in this file and other files in portlet and it returns the number I selected.

I check in "view-entries.jsp", I saw in the SearchContainer, but I show the default petal, I update by lPortletInstanceSettings.getEntriesPerPage(). Now it works with my expectation.

**Comment by thuycao99** [comment]
Hi @huynguyen-codeengine,
Do you have any comments or other solutions for this bug?

**Comment by huynguyen-codeengine** [comment]
Ok, looks good

**Pull request closed without merging**
