### PR TITLE
LPS-161386 Link To URL page with target doesn't open in new tab on page admin

### PR DESCRIPTION
**Pull request by ces-locpham**
HI @ces-huynguyen ,
Could you review my [ticket](https://issues.liferay.com/browse/LPS-161386?filter=53243)?
Thanks.

### CODE REVIEW

**Comment by ces-huynguyen** [comment]
Target field is empty when switch Target type to "New tab" then switch back

**Comment by locpham97** [comment]
Hi @ces-huynguyen ,
I just have updated the source code to fix the target field is empty. 
Thanks

**Comment by ces-huynguyen** [comment]
ci:test

**Comment by ces-huynguyen** [comment]
Forwarded here https://github.com/liferay-echo/liferay-portal/pull/9434

**Pull request closed without merging**
