### PR TITLE
Prompt 2.1 - DM Folder Name WCM Collab Prompt

### PR DESCRIPTION
**Pull request by chileces**
Steps to Reproduce
1. Add a Documents and Media portlet to a page.
2. Create a new Document Folder with an Ampersand in the folder's name.
3. Set the Documents and Media portlet to Icon view.

Expected:
Ampersand will display correctly.
Actual:
Ampersand displays as its escaped version instead.

Additional Instructions: After reproducing, fix the issue on your own branch, run the source formatter, then send your mentor a PR over GitHub.

https://github.com/holatuwol/liferay-portal/tree/debug-prompt-wcm-dm-folder-name

### CODE REVIEW

**Comment by chileces** [comment]
@huynguyen-codeengine please help me to review this task

**Comment by chileces** [comment]
@chileces followup this PR

**Comment by huynguyen-codeengine** [comment]
There are other instances of liferay-frontend:horizontal-card in the portal that also have HtmlUtil.escape called in setting the text attribute.

Were you able to check to see if the bug also affects any of those other portlets?

**Comment by chileces** [comment]
@huynguyen-codeengine thank you, i will try to reproduce on this

**Comment by chileces** [comment]
@huynguyen-codeengine please help me to review

**Comment by huynguyen-codeengine** [comment]
Can you group 3 to 1 commit ?

**Comment by chileces** [comment]
@huynguyen-codeengine I rebased these commits into one. please help me to review it

**Comment by huynguyen-codeengine** [comment]
LGTM

**Pull request closed without merging**
