### PR TITLE
LPS-139624 Friendly Url field should not be displayed in the global scope web content.

### PR DESCRIPTION
**Pull request by ces-quanhuynh**
When you create web content in the global scope, there is no option to select a display page template but it is possible to specify the friendly URL. This friendly URL field has no meaning for web content in the global scope. This might lead the users to misunderstand that there is a way to refer to content from a friendly URL. So we should disable this field in globle scope to avoid that misunderstanding. 
The way to disable this field is like the way to fix the issue [LPS-100472](https://issues.liferay.com/browse/LPS-100472).

### CODE REVIEW

**Comment by huynguyen-codeengine** [comment]
@quanhuynhces 
could you refactor code to avoid duplicate.

**Comment by quanhuynhces** [comment]
@huynguyen-codeengine 
I have refactored it. Please review.

**Comment by quanhuynhces** [comment]
I have changed with the GroupLocalServiceUtil class. Please review again. Thanks.

**Comment by huynguyen-codeengine** [comment]
Foward PR, please follow https://github.com/holatuwol/liferay-portal/pull/248

**Pull request closed without merging**
