### PR TITLE
Prompt 4.1 - Calendar Permission Prompt for New TSE

### PR DESCRIPTION
**Pull request by chileces**
Steps to reproduce:
"Calendar is temporarily unavailable" message is shown when a user doesn't has permissions to watch a calendar.
1.- Add the calendar portlet to a page.
2.- Create a new Resource by going to the Resource tab and clicking "Add Resource" and naming it "My New Resource" and saving.
3.- Back on the Calendar tab, add the calendar related to that resource on the section "Other calendars" by typing "My New Resource"
4.- Create a new regular user through the Control Panel and add them to the Liferay site under Edit User > Sites.
5.- From the Users and Organization menu, impersonate the regular user on another tab and ensure that the new calendar is shown on the calendar portlet, otherwise repeat step 3 as the regular user so that it appears.
6.- As admin on the Calendar portlet, click on the "My New Resource" calendar arrow, and remove permissions on that calendar to everyone except to owner.
7.- On the other tab impersonating the regular user, revisit the page where the calendar is.

Expected behavior: the "My New Resource" calendar is not shown.
Current behavior:"Calendar is temporarily unavailable" message is shown

Solution:
Due to Insufficient permission for the user with an asset, a Principal exception is thrown from the core SB, I add a  try-catch block in the calendar web client code to handle this case.

### CODE REVIEW

**Comment by chileces** [comment]
@huynguyen-codeengine please help me to review this ticket

**Comment by huynguyen-codeengine** [comment]
Failed source format. Run:
ant setup-sdk compile 
cd portal-impl 
ant format-source-latest-author

**Comment by chileces** [comment]
@huynguyen-codeengine force push code formatted

**Comment by huynguyen-codeengine** [comment]
LGTM.

**Pull request closed without merging**
